#pragma once

#include <Util\Array2D.h>

#include <SFML\Graphics\Sprite.hpp>

#include <set>
#include <tuple>
#include <map>

namespace GB {

    // This gets used by the Cluster generator.
    struct ClusterGenerationOptions {
        // What cluster is displayed as (could be sprite later)
        sf::Color colorOfCluster;
        // percent of points to be this cluster
        int percent;
    };

    class Cluster {
    public:
        // also functions as the setter
        // random number generated by caller is passed in
		Cluster(std::pair<int, int> firstPoint, std::multimap<std::pair<int, int>, Cluster>& pointToClusterMap, std::pair<int, int> dimensions);

        //getter
		std::set<std::pair<int, int>>* Cluster::getClusterPoints();

		ClusterGenerationOptions* getClusterGenerationOptions();

        //setter
		void setClusterGenerationOptions(ClusterGenerationOptions* OptionsForThisCluster);

		bool addPointToCluster(int randomNumber);

    private:
        // This moves the border's iterator some number, maintaining the circular border
		void moveIterator(int& numberToMove);

		void UpdateBorder(std::pair<int, int> pointToAdd);

        // Dimensions of the graph
        std::pair<int, int> dimensionsOfGrid;
        std::multimap<std::pair<int, int>, Cluster>* pointToClusterMap;

        // Set of all points of the Array2D which are owned by this cluster
        std::set<std::pair<int, int>> clusterPointSet;

        std::set<std::pair<int, int>> borderPointSet;
        std::set<std::pair<int, int>>::iterator borderPointSetIter;

        ClusterGenerationOptions clusterOptions;
    };
}