#include <Util\Array2D.h>
#include <Util\Cluster.h>
#include <Util\Point.h>

#include <SFML\Graphics\Sprite.hpp>

#include <set>
#include <tuple>
#include <map>

using namespace GB;

// also functions as the setter
// random number generated by caller is passed in
Cluster::Cluster(Point2D<int> firstPoint, Point2D<int> dimensions, std::multimap<Point2D<int>, Cluster>& pointToClusterMap) {
    this->pointToClusterMap = &pointToClusterMap;
    dimensionsOfGrid = dimensions;
    clusterPointSet.insert(firstPoint);
    UpdateBorder(firstPoint);
    //this->pointToClusterMap->insert(std::make_pair(firstPoint, *this));
}

//getter
std::set<Point2D<int>>* Cluster::getClusterPoints() {
    return &clusterPointSet;
}

ClusterGenerationOptions* Cluster::getClusterGenerationOptions() {
    return &clusterOptions;
}

//setter
void Cluster::setClusterGenerationOptions(ClusterGenerationOptions* OptionsForThisCluster) {
    clusterOptions = *OptionsForThisCluster;
}

bool Cluster::addPointToCluster(int randomNumber) {
    moveIterator(randomNumber);

    for (int i = 0; i < borderPointSet.size(); i++) {
        // If the point is not already in a different cluster and also not on the edge
        // of the graph, we're good
        if (pointToClusterMap->find(*borderPointSetIter) == pointToClusterMap->end() &&
            dimensionsOfGrid.x > borderPointSetIter->x && dimensionsOfGrid.y > borderPointSetIter->y) {
			Point2D<int> pointToAdd = *borderPointSetIter;
            clusterPointSet.insert(pointToAdd);
            UpdateBorder(pointToAdd);
            pointToClusterMap->insert(std::make_pair(pointToAdd, *this));
            return true;
        }
        // Otherwise, check the next point in the set
        else {
            borderPointSetIter++;
            if (borderPointSetIter == borderPointSet.end()) {
                borderPointSetIter = borderPointSet.begin();
            }
        }
    }

    return false;
}        

// This moves the border's iterator some number, maintaining the circular border
void Cluster::moveIterator(int numberToMove) {
    if (numberToMove >= 0) {
        borderPointSetIter = borderPointSet.begin();
        std::advance(borderPointSetIter, numberToMove);
    }
    else {
        borderPointSetIter = borderPointSet.end();
        std::advance(borderPointSetIter, numberToMove - 1);
    }
}

void Cluster::UpdateBorder(Point2D<int> pointToAdd) {
    borderPointSet.insert(Point2D<int>{pointToAdd.x, pointToAdd.y + 1});
    borderPointSet.insert(Point2D<int>{pointToAdd.x + 1, pointToAdd.y});
    borderPointSet.insert(Point2D<int>{pointToAdd.x, pointToAdd.y - 1});
    borderPointSet.insert(Point2D<int>{pointToAdd.x - 1, pointToAdd.y});
    borderPointSet.erase(pointToAdd);
    borderPointSetIter = borderPointSet.begin();
}

int Cluster::getNumberBorderPoints() {
	return (int)borderPointSet.size();
}