name: GB_CI

on:
  push:
    branches: [ master, develop, feature/GitHubActions ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: setup environment
      run: sudo apt-get install valgrind libpthread-stubs0-dev libgl1-mesa-dev libx11-dev libxrandr-dev libfreetype6-dev libglew1.5-dev libjpeg8-dev libsndfile1-dev libopenal-dev libudev-dev xvfb
    - name: cache dependencies
      run: echo "Cache SFML and TGUI here"
    - name: Build SFML
      run: |
        mkdir SFML
        cd SFML
        git clone --single-branch --branch 2.5.x https://github.com/SFML/SFML.git
        cd SFML
        cmake .
        make
        sudo make install
        cd ../..
    - name: Build Boost
      run: |
        mkdir boost
        cd boost
        wget https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.gz
        tar -xzf boost_1_72_0.tar.gz
        cd boost_1_72_0
        ./bootstrap.sh --with-libraries=test
        sudo ./b2 install

    - name: Build
      run: |
        mkdir GB_Build_Dir
        cd GB_Build_Dir/
        cmake ../GameBackboneSln/ -DGAMEBACKBONE_BUILD_TESTS=ON
        make

    - name: setup Xvfb
    - run: |
      Xvfb :99 &
      export DISPLAY=:99

    - name: Test
      run: |
        ./GameBackboneSln/build/bin/GameBackboneUnitTest
    - name: Valgrind
      run: |
        valgrind ./GameBackboneSln/build/bin/GameBackboneUnitTest
    - name: clang-tidy
      run: echo "Run clang tidy here"
    - name: cppcheck
      run: echo "Run cppcheck here"
    - name: doxygen
      run: echo "Run Doxygen here"
    - name: update VCPKG
      run: echo "update VCPKG here"