name: VERSION_UP

on:
  push:
    branches: [ feature/GitHubActions ]

jobs:
  update_doxygen:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Doxygen
      run: |
        sudo apt install doxygen

    - name: Generate Doxygen
      run: |
        doxygen ./Doxyfile

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.6
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./docs
        publish_branch: test_docs
      