name: VERSION_UP

on:
  push:
    branches: [ feature/GitHubActions ]

jobs:

  add_tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: validate version numbers
      run: |
        echo "validate numbers""


  update_doxygen:
    needs: add_tag
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Doxygen
      run: |
        sudo apt install doxygen

    - name: Generate Doxygen
      run: |
        doxygen ./Doxyfile

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.6
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./docs
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'

  update_vcpkg:
    needs: add_tag
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GB
      uses: actions/checkout@v2
      with:
        path: GameBackbone

    - name: Checkout AG_VCPKG
      uses: actions/checkout@v2
      with:
        repository: lavinrp/ag_vcpkg
        path: ag_vcpkg
        ssh-key: "${{secrets.AG_GITHUB_BOT_KEY}}"
        ref: CI_test
    
    - name: Update VCPKG Port
      run: |
        python3 ./GameBackbone/scripts/UpdateVcpkg.py --sha `git -C ./GameBackbone rev-parse feature/GitHubActions` --gb_port_path ./ag_vcpkg/ports/gamebackbone --gb_path ./GameBackbone
        cd ag_vcpkg
        sudo git config --global user.email "github-actions[bot]@users.noreply.github.com"
        sudo git config --global user.name "github-actions[bot]"
        git add *
        git commit -m "[github-actions] Update GameBackbone"
        git push origin CI_test
